base_path: /apps
preserve_hierarchy: true
export_languages:
  - pl
files:
  - source: "/a/priv/gettext/default.pot"
    dest: /a/default.pot
    translation: "/a/priv/gettext/%two_letters_code%/LC_MESSAGES/default.po"
  - source: "/b/priv/gettext/default.pot"
    dest: /b/default.pot
    translation: "/b/priv/gettext/%two_letters_code%/LC_MESSAGES/default.po"
  - source: "/b/priv/gettext/items.pot"
    dest: /b/items.pot
    translation: "/b/priv/gettext/%two_letters_code%/LC_MESSAGES/items.po"
